version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: weslley
      POSTGRES_PASSWORD: fegulidcas
      POSTGRES_DB: chito_prod
    volumes:
      - postgres_data_chito:/var/lib/postgresql/data
    networks:
      - chito_ntw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "weslley"]
      interval: 10s
      retries: 5
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - chito_ntw
    depends_on:
      postgres:
        condition: service_healthy

networks:
  chito_ntw:
    driver: bridge

volumes:
  postgres_data_chito:
